# Generated by Django 6.0 on 2026-01-18 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, default='09:00', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('artist', 'day_of_week')},
        ),
    ]
