# Generated by Django 6.0 on 2026-04-02 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_workschedule_options_workschedule_break_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooHealingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tattoo_name', models.CharField(max_length=200)),
                ('tattoo_image', models.ImageField(blank=True, null=True, upload_to='healing_tattoos/')),
                ('placement', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
