# Generated by Django 6.0 on 2026-03-11 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    Product = apps.get_model('shop', 'Product')
    
    # Create required categories
    merch, _ = Category.objects.get_or_create(name='Merchandise')
    aftercare, _ = Category.objects.get_or_create(name='Aftercare')
    supplies, _ = Category.objects.get_or_create(name='Supplies')

    # Mapping based on Product.CATEGORY_CHOICES (merch, aftercare, supplies)
    mapping = {
        'merch': merch,
        'aftercare': aftercare,
        'supplies': supplies,
    }

    # Since SQLite already has the strings in the category column/id, we need a way to map them.
    # We'll use a direct SQL update to clear the column if it's invalid OR map them.
    # But wait, if we are in RunPython, we can handle it with ORM if the field hasn't changed *type* in the DB yet?
    # Actually, in SQLite, renaming/altering causes a temporary table usually.
    
    for old_val, obj in mapping.items():
        Product.objects.filter(category=old_val).update(category=obj.id)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_id_alter_orderitem_id_alter_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(convert_categories),
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Processing'), ('shipped', 'Shipped / Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
