# Generated by Django 6.0 on 2026-05-01 20:36

import django.db.models.deletion
from django.db import migrations, models


def clear_old_categories(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    # Clear old string-based category data to avoid FK IntegrityErrors
    Product.objects.all().update(category=None)

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('shop', '0004_alter_product_category_remove_review_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ShopRevenue',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Revenue Summary',
                'verbose_name_plural': 'Shop Revenue Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        # Step 1: Rename old field to legacy to vacate the name
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_legacy',
        ),
        # Step 2: Add new FK field
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
    ]
