# Generated by Django 6.0 on 2026-05-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_shoprevenue_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_legacy',
        ),
    ]
