# Generated by Django 6.0 on 2025-12-06 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_datetime', models.DateTimeField()),
                ('estimated_duration_hours', models.PositiveIntegerField(default=1, help_text='Estimated session length in hours')),
                ('session_type', models.CharField(choices=[('consultation', 'Consultation (15-30 mins)'), ('tattoo', 'Tattoo Session'), ('touchup', 'Touch-up')], default='tattoo', max_length=20)),
                ('tattoo_style', models.CharField(blank=True, help_text='e.g. Traditional, Realism, Fine Line', max_length=100)),
                ('placement', models.CharField(help_text='e.g. Inner Forearm, Ribs', max_length=100)),
                ('size_description', models.CharField(blank=True, help_text='e.g. Palm-size, Full Sleeve', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the design idea')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('reschedule', 'Reschedule Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(limit_choices_to={'is_artist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
