# Generated by Django 6.0 on 2025-12-13 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='artist_notes',
            field=models.TextField(blank=True, help_text='Private notes for the artist (e.g. needle sizes, ink colors)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required deposit amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price_quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Artist's price quote for the session", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Upload a reference photo for the artist', null=True, upload_to='references/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation/rejection', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='placement',
            field=models.CharField(choices=[('arm_outer', 'Outer Arm / Shoulder'), ('forearm', 'Inner Forearm'), ('thigh', 'Thigh'), ('calf', 'Calf'), ('chest', 'Chest'), ('back', 'Back'), ('neck', 'Neck'), ('ribs', 'Ribs / Side'), ('stomach', 'Stomach'), ('hands', 'Hands / Fingers'), ('feet', 'Feet / Ankle'), ('spine', 'Spine')], max_length=100),
        ),
        migrations.CreateModel(
            name='ArtistAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_date', models.DateField(blank=True, help_text='Specific date to close', null=True)),
                ('recurring_weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Block this day of the week every week', null=True)),
                ('reason', models.CharField(default='Unavailable', help_text='e.g. Shop Closed, Holiday', max_length=100)),
                ('artist', models.ForeignKey(limit_choices_to={'is_artist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
