# Generated by Django 6.0 on 2026-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_artist_notes_appointment_deposit_amount_and_more'),
    ]

    operations = [
    ]
