# Generated by Django 6.0 on 2026-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_id_alter_artistavailability_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='artist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='placement',
            field=models.CharField(choices=[('arm', 'Arm'), ('leg', 'Leg'), ('back', 'Back'), ('chest', 'Chest'), ('neck', 'Neck'), ('stomach', 'Stomach'), ('ribs', 'Ribs'), ('other', 'Other')], default='arm', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistavailability',
            name='blocked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistavailability',
            name='reason',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
        migrations.AlterField(
            model_name='artistavailability',
            name='recurring_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
