# Generated by Django 6.0 on 2026-03-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(help_text='Healing day number (1–28)')),
                ('note', models.TextField(help_text='Aftercare instruction for this day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_notes', to='appointment.appointment')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('appointment', 'day')},
            },
        ),
    ]
