# Generated by Django 6.0 on 2026-04-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_healingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(help_text='Day 1–28')),
                ('pain_level', models.PositiveSmallIntegerField(default=0)),
                ('symptoms', models.JSONField(default=list)),
                ('personal_notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_logs', to='appointment.appointment')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('appointment', 'day')},
            },
        ),
        migrations.CreateModel(
            name='HealingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='healing_progress/%Y/%m/')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appointment.healinglog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
