# Generated by Django 6.0 on 2026-05-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_healinglog_artist_feedback_healingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
