# Generated by Django 6.0 on 2026-05-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_is_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='placement',
            field=models.CharField(choices=[('arm_outer', 'Outer Arm / Shoulder'), ('forearm', 'Inner Forearm'), ('thigh', 'Thigh'), ('calf', 'Calf'), ('chest', 'Chest'), ('back', 'Back'), ('neck', 'Neck'), ('ribs', 'Ribs / Side'), ('stomach', 'Stomach'), ('hands', 'Hands / Fingers'), ('feet', 'Feet / Ankle'), ('spine', 'Spine')], default='forearm', max_length=100),
        ),
    ]
