# Generated by Django 6.0 on 2026-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount received for completed appointment', max_digits=10, null=True),
        ),
    ]
